### ISSUE TITLE
Can't connect to server

### ISSUE THREAD

**Issue by bethzoe** [carlalexander/debops-wordpress#106]
Hi there,
I have almost zero knowledge in server admin so have been battling to set this up over the past three days. The latest error I am getting is when I type in debops bootstrap - root it fails to connect to my server everytime and then just kicks me out. I am using the ipaddress as I have not gotten a domain name as yet as I was testing it out to see how it runs.

I have placed my public ssh key on my server.

Any help would be soooooo appreciated! 

Thanks

**Comment by carlalexander** [comment]
What server provider are you using?

**Comment by zedrickvillas** [comment]
Same as mine, the error is
NREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Permission denied (publickey,password).\r\n", "unreachable": true}

Im using Linode as my server.
I guess this is cause by the connectionTimeout.

**Comment by zedrickvillas** [comment]
Here is another error that i encountered.
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/ansible/executor/task_executor.py", line 119, in run
    res = self._execute()
  File "/Library/Python/2.7/site-packages/ansible/executor/task_executor.py", line 441, in _execute
    self._connection = self._get_connection(variables=variables, templar=templar)
  File "/Library/Python/2.7/site-packages/ansible/executor/task_executor.py", line 687, in _get_connection
    connection = self._shared_loader_obj.connection_loader.get(conn_type, self._play_context, self._new_stdin)
  File "/Library/Python/2.7/site-packages/ansible/plugins/__init__.py", line 339, in get
    self._module_cache[path] = self._load_module_source('.'.join([self.package, name]), path)
  File "/Library/Python/2.7/site-packages/ansible/plugins/__init__.py", line 324, in _load_module_source
    module = imp.load_source(name, path, module_file)
  File "/Library/Python/2.7/site-packages/ansible/plugins/connection/paramiko_ssh.py", line 70, in <module>
    import paramiko
  File "/Library/Python/2.7/site-packages/paramiko/__init__.py", line 30, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "/Library/Python/2.7/site-packages/paramiko/transport.py", line 32, in <module>
    from cryptography.hazmat.backends import default_backend
  File "/Library/Python/2.7/site-packages/cryptography/hazmat/backends/**init**.py", line 7, in <module>
    import pkg_resources
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2797, in <module>
    parse_requirements(**requires**), Environment()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 580, in resolve
    raise VersionConflict(dist,req) # XXX put more info here
VersionConflict: (setuptools 1.1.6 (/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python), Requirement.parse('setuptools>=11.3'))

**Comment by carlalexander** [comment]
I'm going to close this. Let me know if you're still having problems @bethzoe!
