### ISSUE TITLE
ImportError: No module named markupsafe

### ISSUE THREAD

**Issue by tmuka** [carlalexander/debops-wordpress#64]
following the doc here, https://github.com/carlalexander/debops-wordpress/wiki/Configuring-your-server, when i run `root@dev:~/debops-wordpress# debops -u root`

i get 

```
root@dev:~/debops-wordpress# debops -u root
Running Ansible playbook from:
/root/.local/share/debops/debops-playbooks/playbooks/site.yml ...
ERROR! Unexpected Exception: No module named markupsafe
the full traceback was:

Traceback (most recent call last):
  File "/usr/local/bin/ansible-playbook", line 79, in <module>
    mycli = getattr(__import__("ansible.cli.%s" % sub, fromlist=[myclass]), myclass)
  File "/usr/local/lib/python2.7/dist-packages/ansible/cli/playbook.py", line 30, in <module>
    from ansible.executor.playbook_executor import PlaybookExecutor
  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/playbook_executor.py", line 27, in <module>
    from ansible.executor.task_queue_manager import TaskQueueManager
  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_queue_manager.py", line 28, in <module>
    from ansible.executor.play_iterator import PlayIterator
  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/play_iterator.py", line 29, in <module>
    from ansible.playbook.block import Block
  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/__init__.py", line 25, in <module>
    from ansible.playbook.play import Play
  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/play.py", line 27, in <module>
    from ansible.playbook.base import Base
  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/base.py", line 32, in <module>
    from jinja2.exceptions import UndefinedError
  File "/usr/local/lib/python2.7/dist-packages/jinja2/__init__.py", line 33, in <module>
    from jinja2.environment import Environment, Template
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 13, in <module>
    from jinja2 import nodes
  File "/usr/local/lib/python2.7/dist-packages/jinja2/nodes.py", line 19, in <module>
    from jinja2.utils import Markup
  File "/usr/local/lib/python2.7/dist-packages/jinja2/utils.py", line 531, in <module>
    from markupsafe import Markup, escape, soft_unicode
ImportError: No module named markupsafe
```

a bit of searching around led me to find a solution running
`pip install markupsafe`

hope this helps!

**Comment by carlalexander** [comment]
There's an [issue](https://github.com/ansible/ansible/issues/13570) about that in the ansible project. It's supposed to be a jinja2 dependency. Maybe something broke recently?

I'll leave this open and do some tests.

**Comment by tmuka** [comment]
cool- thanks for the great project, i'm experimenting with it more today :)

**Comment by ggloveswp** [comment]
Installing markupsafe seems to do the trick for me too, however, when im executing debops -u root again after its installation, i get this error:

Running Ansible playbook from:
/root/.local/share/debops/debops-playbooks/playbooks/site.yml ...
ERROR! the role 'debops.backporter' was not found in /root/.local/share/debops/debops-playbooks/playbooks/env/roles:/root/.local/share/debops/debops-playbooks/playbooks/env:/root/debops-wordpress/roles:/root/debops-wordpress/ansible/roles:/root/.local/share/debops/debops-playbooks/playbooks/../roles:/root/.local/share/debops/debops-playbooks/playbooks/roles:/etc/ansible/roles:/root/.local/share/debops/debops-playbooks/roles

The error appears to have been in '/root/.local/share/debops/debops-playbooks/roles/debops.ruby/meta/main.yml': line 15, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

```
# Backport 'rubygems-integration' package
```
- role: debops.backporter
  ^ here

**Comment by ggloveswp** [comment]
- update: i forced replacement of backporter with this command: ansible-galaxy install debops.backporter --force

and now debops -u root works fine.

**Comment by carlalexander** [comment]
Going to close this for now. Please reopen if you still have the issue.

**Comment by jmssil** [comment]
I got this error message:

`ERROR! Unexpected Exception: No module named markupsafe`

after installing and running ansible.

I found out that the Python files for markupsafe where not in place: /usr/lib/python2.7/dist-packages/markupsafe did not exist.

I solved this with:

`apt reinstall  python-markupsafe`
